name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: yuristaa/belajar-ci-cd:latest
  
  deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Deploy to Production
    run: |
      # Stop and remove existing container
      docker stop my-app-container || true
      docker rm my-app-container || true

      # Pull the latest Docker image
      docker pull yuristaa/belajar-ci-cd:latest

      # Run the new container
      docker run -d --name my-app-container -p 80:80 yuristaa/belajar-ci-cd:latest
